name: JobScrapper Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-with-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate

      - name: Compile TypeScript (Build)
        run: npm run build

      - name: Run Migrations on Test DB
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Run Tests
        env:
          SUPABASEURL: ${{ secrets.SUPABASEURL}}
          SUPARABASEAPI: ${{ secrets.SUPABASEAPI }}
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: npm test

  deploy-to-render:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
