name: JobScrapper - Fetch Jobs Details

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate

      - name: Compile TypeScript (Build)
        run: npm run build

      - name: Run Job Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run scrapJobsDetails
